// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using students_mvc.Data;

#nullable disable

namespace students_mvc.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260517204103_SeedStudents")]
    partial class SeedStudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("students_mvc.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2000, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student01@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ahmed Ali"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2000, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student02@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mohamed Hassan"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2000, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student03@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ali Ibrahim"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student04@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Omar Saleh"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2000, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student05@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Khaled Nour"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2000, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student06@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Youssef Adel"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2000, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student07@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hassan Karim"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2000, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student08@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mahmoud Fahmy"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2000, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student09@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tarek Saeed"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2000, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student10@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sami Mansour"
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(2000, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student11@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ahmed Ali"
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(2001, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student12@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mohamed Hassan"
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(2001, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student13@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ali Ibrahim"
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(2001, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student14@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Omar Saleh"
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(2001, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student15@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Khaled Nour"
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(2001, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student16@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Youssef Adel"
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(2001, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student17@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hassan Karim"
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(2001, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student18@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mahmoud Fahmy"
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(2001, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student19@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tarek Saeed"
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(2001, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "student20@school.com",
                            EnrollmentDate = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sami Mansour"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
