// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using grades_mvc.Data;

#nullable disable

namespace grades_mvc.Data.Migrations
{
    [DbContext(typeof(GradesDbContext))]
    [Migration("20260517204126_SeedGrades")]
    partial class SeedGrades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("grades_mvc.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 83m,
                            StudentId = 1,
                            Subject = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 57m,
                            StudentId = 2,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 56m,
                            StudentId = 3,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 76m,
                            StudentId = 4,
                            Subject = "Mathematics"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 58m,
                            StudentId = 5,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 63m,
                            StudentId = 6,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2025, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 86m,
                            StudentId = 7,
                            Subject = "Mathematics"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2025, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 75m,
                            StudentId = 8,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2025, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 58m,
                            StudentId = 9,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 88m,
                            StudentId = 10,
                            Subject = "Mathematics"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2025, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 61m,
                            StudentId = 11,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2025, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 62m,
                            StudentId = 12,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2025, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 75m,
                            StudentId = 13,
                            Subject = "Mathematics"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2025, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 66m,
                            StudentId = 14,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2025, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 69m,
                            StudentId = 15,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2025, 9, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 63m,
                            StudentId = 16,
                            Subject = "Mathematics"
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2025, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 75m,
                            StudentId = 17,
                            Subject = "Science"
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2025, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 51m,
                            StudentId = 18,
                            Subject = "English"
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2025, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 90m,
                            StudentId = 19,
                            Subject = "Mathematics"
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Score = 78m,
                            StudentId = 20,
                            Subject = "Science"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
